version: '2'
services:
  dprsaleapi:
    build: .
    container_name: dpr.sale_api
    command: python manage.py runserver 0.0.0.0:8002
    ports:
      - 8002:8002
    volumes:
      - /home/django/RealtorNew/uploads:/dprsale/uploads
      #- /home/django/RealtorNew/static:./static
    env_file: .env
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always