# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-28 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Main.Post'),
        ),
    ]
