# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-28 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20170928_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomData',
        ),
    ]
