# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-28 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20170928_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdata',
            name='type',
            field=models.IntegerField(choices=[(0, 'Частное лицо'), (1, 'Риэлтор')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_photo',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='Главное изображение'),
        ),
    ]
