# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-29 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0005_auto_20170928_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='customdata',
            name='type',
            field=models.IntegerField(choices=[(0, 'Частное лицо'), (1, 'Риэлтор')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to='filer.Image',
                                                     verbose_name='Изображение'),
        ),
    ]
