# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-30 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0006_auto_20170929_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdata',
            name='email',
        ),
        migrations.AddField(
            model_name='customdata',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
    ]
