# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-06 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20170930_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='В топе'),
        ),
    ]
