# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-16 16:02
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0008_auto_20171006_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_photo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     to='filer.Image', verbose_name='Главное изображение'),
        ),
    ]
