# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-04 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0009_auto_20171016_1602'),
        ('Main', '0009_post_is_important'),
    ]

    operations = [
    ]
