# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_merge_20180204_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояния',
            },
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Окно',
                'verbose_name_plural': 'Окна',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='balcony',
            field=models.NullBooleanField(verbose_name='Балкон застеклён'),
        ),
        migrations.AddField(
            model_name='post',
            name='corner',
            field=models.NullBooleanField(verbose_name='Угловая'),
        ),
        migrations.AddField(
            model_name='post',
            name='material',
            field=models.ForeignKey(default=django.utils.datetime_safe.date, on_delete=django.db.models.deletion.CASCADE, to='Main.Material', verbose_name='Материал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.ForeignKey(default=django.utils.datetime_safe.date, on_delete=django.db.models.deletion.CASCADE, to='Main.State', verbose_name='Состояние'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='window',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Main.Window', verbose_name='Окно'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together=set([('verified', 'closed')]),
        ),
    ]
