# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_merge_20180204_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Living_space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Жилая площадь',
                'verbose_name_plural': 'Жилые площади',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояния',
            },
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Окно',
                'verbose_name_plural': 'Окна',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='balcony',
            field=models.NullBooleanField(verbose_name='Балкон застеклён'),
        ),
        migrations.AddField(
            model_name='post',
            name='corner',
            field=models.NullBooleanField(verbose_name='Угловая'),
        ),
        migrations.AlterField(
            model_name='post',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.District', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='post',
            name='storeys',
            field=models.PositiveSmallIntegerField(default=1, null=True, verbose_name='Этажность здания'),
        ),
        migrations.AddField(
            model_name='post',
            name='living_space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Living_space', verbose_name='Жилая площадь'),
        ),
        migrations.AddField(
            model_name='post',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Material', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.State', verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='post',
            name='window',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Window', verbose_name='Окно'),
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together=set([('verified', 'closed')]),
        ),
    ]
