# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0011_auto_20180415_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post', name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Стоимость'),
        ),
    ]
