# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 22:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20180405_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.date.today, null=True, verbose_name='Дата создания'),
        ),
    ]
