# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20180430_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
