# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0015_remove_post_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='currency_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.Currency',
                                    verbose_name='Валюта'),
        ),
    ]
