# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_post_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.Currency', verbose_name='Валюта'),
        ),
    ]
