# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-05 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_auto_20180501_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='corner',
            field=models.BooleanField(default=False, verbose_name='Угловая'),
        ),
    ]
