# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-05 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_auto_20180505_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='post',
            name='contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='post',
            name='kitchen_square',
            field=models.FloatField(blank=True, null=True, verbose_name='Кухонная площадь (метры кв.)'),
        ),
        migrations.AddField(
            model_name='post',
            name='landmark',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ориентир'),
        ),
        migrations.AddField(
            model_name='post',
            name='living_square',
            field=models.FloatField(blank=True, null=True, verbose_name='Жилая площадь (метры кв.)'),
        ),
        migrations.AddField(
            model_name='post',
            name='loggia',
            field=models.NullBooleanField(verbose_name='Лоджия застеклена'),
        ),
        migrations.AddField(
            model_name='post',
            name='private_description',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии от риелтора'),
        ),
        migrations.AddField(
            model_name='post',
            name='total_square',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая площадь (метры кв.)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Рекомендованное'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.State', verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='post',
            name='window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Window', verbose_name='Окно'),
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='post',
            name='living_space',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='post',
            name='square',
        ),
        migrations.RemoveField(
            model_name='post',
            name='verified',
        ),
    ]
