# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-05 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0020_auto_20180505_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treecategory',
            options={'verbose_name': 'Дерево категорий', 'verbose_name_plural': 'Деревья категорий'},
        ),
        migrations.RemoveField(
            model_name='customdata',
            name='type',
        ),
        migrations.RemoveField(
            model_name='customdata',
            name='verified',
        ),
    ]
