# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-10 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0021_auto_20180505_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='Main.TreeCategory', verbose_name='Дерево состояний'),
        ),
    ]
