# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-19 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0022_post_category_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=3, verbose_name='Символ'),
        ),
        migrations.AlterField(
            model_name='image',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Main.Post'),
        ),
    ]
