# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-19 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_auto_20180519_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='prefix',
            field=models.BooleanField(default=False, verbose_name='Префиксный символ'),
        ),
    ]
