# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-27 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0023_auto_20180519_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Living_space',
        ),
    ]
