# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-19 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_currency_prefix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='prefix',
            new_name='is_prefix',
        ),
    ]
