# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 10:39
from __future__ import unicode_literals

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Post = apps.get_model("Main", "Post")
    db_alias = schema_editor.connection.alias
    Post.objects.filter(category__in=[1, 2]).update(category_tree=10)
    Post.objects.filter(category=3).update(category_tree=8)
    Post.objects.filter(category=6).update(category_tree=4)
    Post.objects.filter(category=7).update(category_tree=2)

class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_post_category_tree'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
