# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-27 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_old_categories_to_new'),
        ('Main', '0024_delete_living_space'),
    ]

    operations = [
    ]
