# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-15 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0027_auto_20180619_0827'),
        ('Main', '0027_auto_20180630_1244'),
    ]

    operations = [
    ]
