# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-15 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0028_merge_20180715_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miniimage',
            options={'verbose_name': 'Пикча для теста', 'verbose_name_plural': 'Пикчи для теста'},
        ),
        migrations.AddField(
            model_name='post',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='post',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Закрыто'),
        ),
    ]
