# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-15 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0030_auto_20180715_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='closed',
            new_name='is_closed',
        ),
    ]
