# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-05 10:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_auto_20180715_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='calendar',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ranges.DateRangeField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
    ]
