# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-05 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0033_auto_20180805_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
