# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-05 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0035_auto_20180805_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('sort_order',)},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='obj',
            new_name='product',
        ),
        migrations.AddField(
            model_name='image',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
