# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-05 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import os

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Image = apps.get_model("Main", "Image")
    db_alias = schema_editor.connection.alias
    Image.objects.using(db_alias).filter(sort_order=0).update(sort_order=1)




def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0038_manual_filer_to_image'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]

