# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-05 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import os

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Post = apps.get_model("Main", "Post")
    Image = apps.get_model("Main", "Image")
    db_alias = schema_editor.connection.alias
    qs = Post.objects.using(db_alias).all()
    for obj in qs:
        if obj.main_photo is not None:
            try:
                print(obj.main_photo.file)

                img = Image()
                img.sort_order = 0
                img.product_id = obj.id
                img.image_file = 'img/' + str(obj.main_photo.file)

                img.save()
            except:
                print(f'Leave {obj.main_photo.file}')




def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0039_manual_sort_order'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]



