# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-05 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0040_manual_filer_to_image_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='main_photo',
        ),
    ]
