# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-06 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0041_remove_post_main_photo'),
        ('Main', '0033_auto_20180805_2032'),
    ]

    operations = [
    ]
