# Generated by Django 2.0.8 on 2018-08-09 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0042_merge_20180806_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя')),
                ('decription', models.TextField(max_length=256, verbose_name='Описание')),
                ('phone_one', models.CharField(blank=True, max_length=25, null=True, verbose_name='Первый номер телефона')),
                ('phone_two', models.CharField(blank=True, max_length=25, null=True, verbose_name='Второй номер телефона')),
                ('phone_three', models.CharField(blank=True, max_length=25, null=True, verbose_name='Третий номер телефона')),
                ('phone_four', models.CharField(blank=True, max_length=25, null=True, verbose_name='Четвёртый номер телефона')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.RemoveField(
            model_name='miniimage',
            name='main_photo',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.TreeCategory', verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='post',
            name='currency_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.Currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='post',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.Material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(43), to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.State', verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='post',
            name='window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.Window', verbose_name='Окно'),
        ),
        migrations.DeleteModel(
            name='MiniImage',
        ),
        migrations.AddField(
            model_name='post',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.Client', verbose_name='Клиент'),
        ),
    ]
