# Generated by Django 2.0.8 on 2018-08-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0043_auto_20180809_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='Main.District', verbose_name='Район'),
        ),
    ]
